### ISSUE TITLE
Model-driven Mapbook

### ISSUE THREAD

**Issue by stlim0730** [stlim0730/farmview#10]
Adam,

I deployed my local branch to the production server for test. https://farmview.herokuapp.com/
On the admin panel (https://farmview.herokuapp.com/admin), you can add/delete/edit Mapbook items. I put one entry as an example.

If you confirm this feature, I'll merge this branch into master and redeploy master on the server. Questions are welcomed!

**Comment by calo1** [comment]
Taek,  this is great! Please merge and I'll add new maps.  Although there
was some previous text on the conservation easement map that I would like
to find.  Where can i see the code of Karin's version?

Questions:

(1)  Does the thumbnail image automatically fit the predetermined size or
do you have to preselect a square image of certain pixel size?

(2) Can the text accept hyperlinks with markdown in the admin tool?


(3) Lower priority:  Could this model in the future accept cartodb.js
instead of the simple iframe?  Or would we need to lin to a separate
template for more custom maps?



On Tue, Feb 23, 2016 at 6:44 PM, stlim0730 <notifications@github.com> wrote:

> Adam,
>
> I deployed my local branch to the production server for test.
> https://farmview.herokuapp.com/
> On the admin panel (https://farmview.herokuapp.com/admin), you can
> add/delete/edit Mapbook items. I put one entry as an example.
>
> If you confirm this feature, I'll merge this branch into master and
> redeploy master on the server. Questions are welcomed!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stlim0730/farmview/issues/10>.
>



-- 
Adam Calo
PhD Candidate
Dept of Environmental Science, Policy, & Management
UC Berkeley
130 Mulford Hall #3114
Berkeley, CA 94720
adamcalo@berkeley.edu

**Comment by stlim0730** [comment]
Adam, I hope you have added / removed new entries of Mapbook for test on the admin panel (try if you haven't). Let me merge and close this issue after brief discussion in the meeting tomorrow.

1) It automatically fits; the width of an image will be one third of the grid with three thumbnails in a row. It doesn't need to be a square image. The image will proportionally shrink to have the acceptable width.

2) It doesn't currently accept HTML or markdown. To support HTML takes 1 minute (literally), but markdown takes a week or two. Do you want to put HTML in the text?

3) Yes. No technical concerns or difficulty, but minor usability issue comes up. If you don't think the tool is giving too much control to a user, we can definitely use CartoDB.js for Mapbook to increase general interactivity of the tool.

I found a minor bug; map title right above the iframe has the same color as the background. I'll fix it.

**Comment by stlim0730** [comment]
Oh, the Karin's code with the text and iframe of the maps are still in mapbook.html. I commented them out, but not delete.

**Comment by calo1** [comment]
I tested the mapbook model it and it works nicely.  I'm not sure if the
thumbnail url can be any url or it has to be stored on the server as well.


HTML is fine for the text. I' expect mostly links and perhaps an image or
two.

All i need is a copy paste of the text from the previous version.

See you tomorrow,

Adam


On Wed, Feb 24, 2016 at 12:12 PM, stlim0730 <notifications@github.com>
wrote:

> Oh, the Karin's code with the text and iframe of the maps are still in
> mapbook.html. I commented them out, but not delete.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stlim0730/farmview/issues/10#issuecomment-188436927>.
>



-- 
Adam Calo
PhD Candidate
Dept of Environmental Science, Policy, & Management
UC Berkeley
130 Mulford Hall #3114
Berkeley, CA 94720
adamcalo@berkeley.edu
