### ISSUE TITLE
Bofan is absent from this project

### ISSUE THREAD

**Issue by calo1** [stlim0730/farmview#17]
Bofan is gone!  We need his help.   We have a great project for him.  If only he would work on this experiential opportunity he would really learn and get great credentials.

**Comment by bofie123** [comment]
Hi, Adam! What project is it?  I can't guarentee I'm able to chip in tho :(, cuz coursework has been killing me lately. But I might be able to work on it over Spring Break. Please let me know details about the project when you've time! Thanks!

**Comment by stlim0730** [comment]
Hi, @bofie123. We wanted to ping you because we found a relatively well-defined subproject. I'm just curious whether you're taking any project-based courses in CS. If you are, it might be nice to talk about how to get the subproject aligned with your class project. No pressure at all, but potentially a good opportunity. Do you take courses with final projects?

**Comment by bofie123** [comment]
Hmm, last semester I was taking a project-based course that had a final project, but this semester I'm not..

**Comment by stlim0730** [comment]
We have three other collaborators for this summer. Still miss Bofan, but it's okay for now with the awesome new people. I'm closing this issue.
