### ISSUE TITLE
Table is not created

### ISSUE THREAD

**Issue by sohyeonlee** [stlim0730/farmview#42]
ProgrammingError at /admin/map/formdata/
relation "map_formdata" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "map_formdata"
                                          ^
Request Method:	GET
Request URL:	http://127.0.0.1:8000/admin/map/formdata/
Django Version:	1.9.7
Exception Type:	ProgrammingError
Exception Value:	
relation "map_formdata" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "map_formdata"
                                          ^
Exception Location:	/Users/irenelee/Desktop/projects/farmview/vir/lib/python2.7/site-packages/django/db/backends/utils.py in execute, line 64
Python Executable:	/Users/irenelee/Desktop/projects/farmview/vir/bin/python
Python Version:	2.7.10
Python Path:	
['/Users/irenelee/Desktop/projects/farmview',
 '/Users/irenelee/Desktop/projects/farmview/vir/lib/python27.zip',
 '/Users/irenelee/Desktop/projects/farmview/vir/lib/python2.7',
 '/Users/irenelee/Desktop/projects/farmview/vir/lib/python2.7/plat-darwin',
 '/Users/irenelee/Desktop/projects/farmview/vir/lib/python2.7/plat-mac',
 '/Users/irenelee/Desktop/projects/farmview/vir/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/irenelee/Desktop/projects/farmview/vir/Extras/lib/python',
 '/Users/irenelee/Desktop/projects/farmview/vir/lib/python2.7/lib-tk',
 '/Users/irenelee/Desktop/projects/farmview/vir/lib/python2.7/lib-old',
 '/Users/irenelee/Desktop/projects/farmview/vir/lib/python2.7/lib-dynload',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/irenelee/Desktop/projects/farmview/vir/lib/python2.7/site-packages']
Server time:	Mon, 18 Jul 2016 16:51:09 -0700

I get this error when I try populating data into new Formdata model. The table is not created and not sure how to.

**Comment by stlim0730** [comment]
@sohyeonlee, let me take a look at this issue. I need some information. Could you share the data (the ids and url) for the model you defined with me?

**Comment by stlim0730** [comment]
@sohyeonlee, okay. I got something minor, but with potentially significant effects: indentation.

The fix:

1. `models.py`, and other source codes I composed, has two-space indentation. What I saw in your `FormData` class in `models.py` was four-space. Make it two for in-file consistency because upper part of the file has it.
2. dropbox_url is defined as CharField, which requires max_length by definition. pass a keyword parameter of `max_length`, just like you did below the line (`optional_note = models.CharField(max_length=200, blank = True)`)
3. After that, I was able to do `python manage.py makemigrations map` and `python manage.py migrate` without any errors.

Hope this helps. Let me know how it goes!

**Comment by calo1** [comment]
@sohyeonlee Any luck with Taek's method?

**Comment by hyeonishl** [comment]
Cool. It works now thank you!

**Comment by sohyeonlee** [comment]
Cool. It works now thank you!

**Comment by stlim0730** [comment]
Good. Closing this issue. Feel free to open other issues if you have any.
