### ISSUE TITLE
Farmview Down?

### ISSUE THREAD

**Issue by calo1** [stlim0730/farmview#5]
I just made an appeal to get some farmers to test the app.. so hopefully this could be addressed?
Error message:

An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.

**Comment by stlim0730** [comment]
Must be Heroku issue... I'm on it.

**Comment by stlim0730** [comment]
Resolved. The app's running (https://farmiew.herokuapp.com)

The reason was that Bofan and I seemed to have different copy of the code, which was caused by some sort of merging operation of git, for some reason. You know, merging is always where conflicts occur. The latest commit doesn't have the 'import_export' package issue, so everyone in this repo should pull the master branch or clone the repo again before working on any tiny things in this code base.

Adam, test the app and close this issue. Thanks for your prompt bug report!

**Comment by calo1** [comment]
Tested app and is running! good sleuthing.
