### ISSUE TITLE
No modules named 'Comments'

### ISSUE THREAD

**Issue by sohyeonlee** [stlim0730/farmview#62]
So I have pulled the recent version, and when I try to run to fix/repro issues with my code, I keep getting error: No modules name comments. Wasn't sure where this is used or the error just appears to me. 

I have google searched and included that 'django.contrib.comments' in INSTALLED_APPS in settings.py, did pip install but no luck. 

If it's just me getting the error, how should I resolve this? 

<img width="950" alt="screen shot 2016-07-26 at 6 11 00 pm" src="https://cloud.githubusercontent.com/assets/5906951/17160807/c2e8964e-535c-11e6-8ebd-092207458141.png">

**Comment by stlim0730** [comment]
@sohyeonlee,

So, another fault of mine along with this #59 was not sharing workflow and dependency control with you at the beginning of the summer. What all of us should have done was, to be on the same page in terms of package dependency, more carefully managing requirements.txt. :( Sorry about that.

My `settings.py` has `'django_comments'` rather than `'django.contrib.comments'` in `INSTALLED_APPS`. Give it a try.

Put `django-contrib-comments==1.7.1` in `requirements.txt`. And then,

```
$ pip install -r requirements.txt
```
will install all the packages you specified in the file, including comment module. @calo1, @sohyeonlee, @nutelIa, and @kbourque, this is how the team should manage the project's package dependency.

This should work. Let me know if you have other questions!

**Comment by sohyeonlee** [comment]
Cool it runs now!
