### ISSUE TITLE
Detail Popup small issues:

### ISSUE THREAD

**Issue by calo1** [stlim0730/farmview#68]
1) On July 30, I'm not seeing detailed info for survey data.  If I try and review detail for data_point I just see the parcel data.  I do see join survey and parcel data on the preview thumbnail popup

2) If you view the detail popup, then close it and then try and open it again, detail popup is blank.  Closing the thumbnail pop-up and re-clicking resolves the issue

**Comment by stlim0730** [comment]
Is this duplicate? (#67)

**Comment by calo1** [comment]
I'm not sure .  I didnt know what the "error" is in #67 so I was documenting my findings in my own words

**Comment by stlim0730** [comment]
So, the problem seems that the new dataset we synced has lost attachment (optional image) or changed the structure of it. I think the latter has higher chance.

Simplest measure: I can disable image attachment in the code.
More complete measure: investigate how the structure has changed and let the code work with it.

@calo1, what do you think?

**Comment by calo1** [comment]
@stlim0730 

Let's try to investigate for a little while.  Fall back is to disable images before the workshop

@karingoh  what is the column name for images supposed to be after your processing script?

**Comment by stlim0730** [comment]
I'm on it.

**Comment by calo1** [comment]
the two photo column names are

photo_filename  and
photolink


I tested the link in `photolink`  and chrome rendered the image correctly

**Comment by stlim0730** [comment]
Fixed.

The app hasn't been using `photolink` data, but `_attachments` because it both has links to the thumbnail and original size image.

The data structure hasn't been changed. Carto used to give it to us in serialized JSON string, but I found it is in JSON object containing serialized JSON string today. Simple fix worked.

... but why now, Carto?
