### ISSUE TITLE
CSS on virtual machine is not updating

### ISSUE THREAD

**Issue by calo1** [stlim0730/farmview#92]
The absence and/or failure to update of css on the local server is preventing some testing and development.

there are two incidents of this happening:

1) about page  changes are not updated
2) admin page no css in sources.

KG is "guessing its any page"

  
![css for admin page](https://user-images.githubusercontent.com/8172009/31200553-3e82c5a4-a910-11e7-96fe-b79ce74cc6ff.png)

**Comment by stlim0730** [comment]
I've identified that this issue was actually two different problems.

1. Undesired cache issue on Nginx on guest machine in dev environment
2. Django issue that didn't properly install admin resources in the project repo

Both are fixed and merged into the latest `master` branch. This issue can be closed upon @calo1 's confirmation.

**Comment by calo1** [comment]
Taek resolved this issue with the rebase
